import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {createLabServer} from '../lab/server.mjs';
import {baselineMap} from '../lab/engine.mjs';
import {localBase,createAgentClient} from '../lab/agent-client.mjs';
const root=path.resolve(import.meta.dirname,'..');
async function start(t,env={},agentOptions={}){
 const home=fs.mkdtempSync(path.join(os.tmpdir(),'tao-agent-test-')),server=createLabServer({home,env,agentOptions});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const base=`http://127.0.0.1:${server.address().port}`;
 const req=async(p,b,token)=>{const q=await fetch(base+p,{method:b===undefined?'GET':'POST',headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{})},body:b===undefined?undefined:JSON.stringify(b)});return {status:q.status,data:await q.json()};};
 t.after(async()=>{server.closeStreams();await new Promise(r=>server.close(r));fs.rmSync(home,{recursive:true,force:true});});
 return {base,home,server,req,tool:(token,name,b={})=>req('/api/agent/tools/observatory_'+name,b,token)};
}
async function attach(lab,{role='analyst',mode='guided',maxJobs=12}={}){
 const run=(await lab.req('/api/demo',{})).data.run,observation=run.observations[0];
 const setup=await lab.req('/api/agent/sessions',{runId:run.id,role,mode,maxJobs});assert.equal(setup.status,201,JSON.stringify(setup.data));
 const c=await lab.req('/api/agent/connect',{code:setup.data.pairing.code,client:{name:'Test Agent',version:'1',model:'simulated-external'}});assert.equal(c.status,200);
 return {run,observation,session:setup.data.session,code:setup.data.pairing.code,token:c.data.accessToken};
}
async function queue(lab,x,kind='mapping',op,force=false){const q=await lab.req(`/api/runs/${x.run.id}/agent-jobs`,{observationId:x.observation.id,kind,operatorId:op,force});assert.equal(q.status,201,JSON.stringify(q.data));return q.data;}
async function claim(lab,x){const q=await lab.tool(x.token,'next_task');assert.equal(q.status,200,JSON.stringify(q.data));assert.equal(q.data.state,'claimed',JSON.stringify(q.data));return q.data;}
const envelope=(j,result,key='a')=>({jobId:j.job.id,claimToken:j.claimToken,contextHash:j.contextHash,idempotencyKey:key,result});
const insight=o=>({headline:'验证能力可能成为新约束',text:'如果编码提速但评审仍积压，验证能力可能成为新的约束。',alternative:'任务数量变化也可能造成积压。',verificationSignal:'比较同类任务的评审耗时。',refutationSignal:'评审并非瓶颈时削弱该解释。',evidence:['评审积压从 8 项增加到 21 项']});
async function mapped(lab,x){await queue(lab,x);const j=await claim(lab,x);const q=await lab.tool(x.token,'submit_result',envelope(j,{mapping:baselineMap(x.observation)}));assert.equal(q.status,200,JSON.stringify(q.data));return j;}
function cli(lab,args){return new Promise((resolve,reject)=>{const p=spawn(process.execPath,['lab/cli.mjs',...args],{cwd:root,env:{...process.env,TAO_LAB_URL:lab.base}});let stdout='',stderr='';p.stdout.on('data',s=>stdout+=s);p.stderr.on('data',s=>stderr+=s);p.on('error',reject);p.on('close',code=>resolve({code,stdout,stderr}));});}

test('external connect pins real theory and rejects reusing a one-time code',async t=>{const lab=await start(t),x=await attach(lab);const q=await lab.tool(x.token,'get_context');assert.equal(q.status,200);assert.match(q.data.context.constitution,/第一条 生存/);assert.match(q.data.context.protocol,/Insight operators/);assert.equal(q.data.context.constitutionHash.length,64);assert.equal(q.data.context.observations[0].id,x.observation.id);assert.equal((await lab.req('/api/agent/connect',{code:x.code})).status,401);});
test('pair and bearer secrets do not appear in run export or session list',async t=>{const lab=await start(t),x=await attach(lab);for(const p of ['/api/runs/'+x.run.id+'/export','/api/agent/sessions']){const s=JSON.stringify((await lab.req(p)).data);assert.ok(!s.includes(x.token));assert.ok(!s.includes(x.code));assert.ok(!s.includes('tokenHash'));}const stored=fs.readFileSync(path.join(lab.home,'agent','sessions.json'),'utf8');assert.ok(!stored.includes(x.token));assert.ok(stored.includes('tokenHash'));});
test('scoped API requires token and rejects token use on owner endpoints',async t=>{const lab=await start(t),x=await attach(lab);assert.equal((await lab.req('/api/agent/status')).status,401);assert.equal((await lab.req('/api/agent/status',undefined,'wrong')).status,401);assert.equal((await lab.req('/api/runs/'+x.run.id+'/feedback',{},x.token)).status,403);assert.equal((await lab.req('/api/agent/sessions',{},x.token)).status,403);});
test('Guided agents cannot create their own mapping or insight tasks',async t=>{const lab=await start(t),x=await attach(lab);const q=await lab.tool(x.token,'request_task',{observationId:x.observation.id,kind:'mapping'});assert.equal(q.status,403);assert.equal(q.data.code,'HUMAN_REQUEST_REQUIRED');assert.equal((await lab.tool(x.token,'next_task')).data.state,'idle');});
test('external driver blocks legacy live AND baseline endpoints without fallback',async t=>{const lab=await start(t,{TAO_LLM_ENABLED:'1',TAO_LLM_URL:'http://127.0.0.1:1/v1/chat/completions',TAO_LLM_MODEL:'never-called'}),x=await attach(lab);for(const allowLive of [true,false]){const q=await lab.req(`/api/runs/${x.run.id}/observations/${x.observation.id}/map`,{allowLive});assert.equal(q.status,409);assert.equal(q.data.code,'EXTERNAL_DRIVER_ACTIVE');}await mapped(lab,x);const r=(await lab.req('/api/runs/'+x.run.id)).data.run;assert.equal(r.traces.length,0);assert.equal(r.mappingMeta[x.observation.id].provider,'external');});
test('human queue is deduplicated and claiming returns full context plus a lease',async t=>{const lab=await start(t),x=await attach(lab);const a=await queue(lab,x),b=await queue(lab,x);assert.equal(a.job.id,b.job.id);assert.equal(b.reused,true);const j=await claim(lab,x);assert.equal(j.context.observation.rawContent,x.observation.rawContent);assert.equal(j.contextHash.length,64);assert.ok(j.claimToken);assert.equal((await lab.tool(x.token,'next_task')).data.state,'busy');assert.ok(!JSON.stringify((await lab.req('/api/runs/'+x.run.id)).data).includes(j.claimToken));});
test('six cards and an insight submitted by external AI share persisted server state',async t=>{const lab=await start(t),x=await attach(lab);await mapped(lab,x);await queue(lab,x,'insight','migration');const j=await claim(lab,x),q=await lab.tool(x.token,'submit_result',envelope(j,insight(x.observation)));assert.equal(q.status,200,JSON.stringify(q.data));const r=(await lab.req('/api/runs/'+x.run.id)).data.run;assert.equal(r.insights.length,1);assert.equal(r.hypotheses.length,1);assert.equal(r.insights[0].provider,'external');assert.equal(r.insights[0].contextHash,j.contextHash);assert.equal(r.agentSubmissions.length,2);assert.equal(r.traces.length,0);assert.equal(r.agentJobs.filter(j=>j.state==='completed').length,2);});
test('invalid evidence is audited, preserves empty map and can be corrected',async t=>{const lab=await start(t),x=await attach(lab);await queue(lab,x);const j=await claim(lab,x),bad=baselineMap(x.observation);bad.S.evidence='原文不存在的内容';const q=await lab.tool(x.token,'submit_result',envelope(j,{mapping:bad},'bad'));assert.equal(q.status,422);let r=(await lab.req('/api/runs/'+x.run.id)).data.run;assert.equal(r.agentSubmissions[0].accepted,false);assert.equal(Object.keys(r.mappings).length,0);assert.equal(r.agentJobs[0].state,'needs_revision');const good=await lab.tool(x.token,'submit_result',envelope(j,{mapping:baselineMap(x.observation)},'fixed'));assert.equal(good.status,200);r=(await lab.req('/api/runs/'+x.run.id)).data.run;assert.equal(r.agentSubmissions.length,2);assert.equal(r.agentSubmissions[0].result.mapping.S.evidence,'原文不存在的内容');assert.equal(r.traces.length,0);});
test('partial/malformed six-card shapes remain auditable rather than being auto-completed',async t=>{const lab=await start(t),x=await attach(lab);await queue(lab,x);const j=await claim(lab,x),q=await lab.tool(x.token,'submit_result',envelope(j,{mapping:{S:{}}}));assert.equal(q.status,422);const r=(await lab.req('/api/runs/'+x.run.id)).data.run;assert.equal(r.agentJobs[0].state,'needs_revision');assert.equal(r.agentSubmissions.length,1);assert.equal(Object.keys(r.mappings).length,0);});
test('N cannot be OBSERVED; submitted extra fields cannot spoof agent metadata',async t=>{const lab=await start(t),x=await attach(lab);await queue(lab,x);const j=await claim(lab,x),map=baselineMap(x.observation);map.N.state='OBSERVED';assert.equal((await lab.tool(x.token,'submit_result',envelope(j,{mapping:map},'a'))).status,422);assert.equal((await lab.tool(x.token,'submit_result',envelope(j,{mapping:baselineMap(x.observation),provider:'human'},'b'))).status,422);});
test('same idempotency key/payload returns accepted result without duplicate event',async t=>{const lab=await start(t),x=await attach(lab);await queue(lab,x);const j=await claim(lab,x),b=envelope(j,{mapping:baselineMap(x.observation)});assert.equal((await lab.tool(x.token,'submit_result',b)).status,200);const before=(await lab.req('/api/runs/'+x.run.id)).data.run;const twice=await lab.tool(x.token,'submit_result',b);assert.equal(twice.data.reused,true);const after=(await lab.req('/api/runs/'+x.run.id)).data.run;assert.equal(after.events.length,before.events.length);assert.equal(after.agentSubmissions.length,1);});
test('idempotency keys cannot be reused for modified output',async t=>{const lab=await start(t),x=await attach(lab);await queue(lab,x);const j=await claim(lab,x),b=envelope(j,{mapping:baselineMap(x.observation)});await lab.tool(x.token,'submit_result',b);b.result.mapping.S.value='Different';assert.equal((await lab.tool(x.token,'submit_result',b)).status,409);});
test('three rejected attempts stop the job; there is no automatic paid retry',async t=>{const lab=await start(t),x=await attach(lab);await queue(lab,x);const j=await claim(lab,x);for(let i=0;i<3;i++)assert.equal((await lab.tool(x.token,'submit_result',envelope(j,{},'a'+i))).status,422);const q=await lab.tool(x.token,'submit_result',envelope(j,{mapping:baselineMap(x.observation)},'a4'));assert.equal(q.status,409);const r=(await lab.req('/api/runs/'+x.run.id)).data.run;assert.equal(r.agentJobs[0].state,'failed');assert.equal(r.agentSubmissions.length,3);assert.equal(r.traces.length,0);});
test('forged claim and context hash are rejected before writes',async t=>{const lab=await start(t),x=await attach(lab);await queue(lab,x);const j=await claim(lab,x),b=envelope(j,{mapping:baselineMap(x.observation)});assert.equal((await lab.tool(x.token,'submit_result',{...b,claimToken:'wrong'})).status,403);assert.equal((await lab.tool(x.token,'submit_result',{...b,contextHash:'a'.repeat(64)})).status,409);assert.equal((await lab.req('/api/runs/'+x.run.id)).data.run.agentSubmissions.length,0);});
test('cancelled work rejects late valid submissions',async t=>{const lab=await start(t),x=await attach(lab);await queue(lab,x);const j=await claim(lab,x);await lab.req(`/api/runs/${x.run.id}/agent-jobs/${j.job.id}/cancel`,{});assert.equal((await lab.tool(x.token,'submit_result',envelope(j,{mapping:baselineMap(x.observation)}))).status,409);assert.equal(Object.keys((await lab.req('/api/runs/'+x.run.id)).data.run.mappings).length,0);});
test('revocation invalidates credentials immediately and preserves pending-task cancellation',async t=>{const lab=await start(t),x=await attach(lab);await queue(lab,x);await lab.req(`/api/agent/sessions/${x.session.id}/revoke`,{});assert.equal((await lab.tool(x.token,'get_context')).status,401);const r=(await lab.req('/api/runs/'+x.run.id)).data.run;assert.equal(r.agentJobs[0].state,'cancelled');assert.equal(r.driver.kind,'external');});
test('switching local is explicit and cancels pending external work',async t=>{const lab=await start(t),x=await attach(lab);await queue(lab,x);await lab.req(`/api/runs/${x.run.id}/driver`,{kind:'local'});assert.equal((await lab.req(`/api/runs/${x.run.id}/observations/${x.observation.id}/map`,{})).status,200);assert.equal((await lab.tool(x.token,'status')).status,401);});
test('only one active writer connection controls a run, while read-only observer may coexist',async t=>{const lab=await start(t),x=await attach(lab);assert.equal((await lab.req('/api/agent/sessions',{runId:x.run.id})).status,409);const q=await lab.req('/api/agent/sessions',{runId:x.run.id,role:'observer'});assert.equal(q.status,201);const c=(await lab.req('/api/agent/connect',{code:q.data.pairing.code})).data;assert.equal((await lab.tool(c.accessToken,'get_context')).status,200);assert.equal((await lab.tool(c.accessToken,'next_task')).status,403);assert.equal((await lab.req('/api/runs/'+x.run.id)).data.run.driver.sessionId,x.session.id);});
test('Analyst cannot ingest, branch, or submit human feedback through MCP tools',async t=>{const lab=await start(t),x=await attach(lab);assert.equal((await lab.tool(x.token,'ingest',{content:'x'})).status,403);assert.equal((await lab.tool(x.token,'branch_run')).status,403);assert.equal((await lab.tool(x.token,'feedback',{rating:'insightful'})).status,404);});
test('Autopilot can request bounded jobs but cannot exceed human-issued quota',async t=>{const lab=await start(t),x=await attach(lab,{mode:'autopilot',maxJobs:1});const q=await lab.tool(x.token,'request_task',{observationId:x.observation.id,kind:'mapping'});assert.equal(q.status,200);const j=await claim(lab,x);await lab.tool(x.token,'submit_result',envelope(j,{mapping:baselineMap(x.observation)}));const b=await lab.tool(x.token,'request_task',{observationId:x.observation.id,kind:'insight',operatorId:'gap'});assert.equal(b.status,409);assert.equal(b.data.code,'JOB_BUDGET_EXCEEDED');});
test('Operator can ingest; branch copies exact frozen context, not conclusions or authorization',async t=>{const lab=await start(t),x=await attach(lab,{role:'operator'});await mapped(lab,x);const q=await lab.tool(x.token,'ingest',{content:'新材料',source:'test'});assert.equal(q.status,200);const b=await lab.tool(x.token,'branch_run',{title:'对照'});assert.equal(b.status,200);const child=(await lab.req('/api/runs/'+b.data.runId)).data.run;assert.equal(child.observations.length,2);assert.equal(child.insights.length,0);assert.equal(child.agentJobs,undefined);assert.equal(child.driver,undefined);assert.equal(child.promptSnapshot.sha256,x.run.promptSnapshot.sha256);assert.equal((await lab.tool(x.token,'get_context',{observationId:'obs_not_in_scope'})).status,404);});
test('agent-added evidence has external provenance, never human provenance',async t=>{const lab=await start(t),x=await attach(lab);await mapped(lab,x);await queue(lab,x,'insight','gap');const j=await claim(lab,x),made=await lab.tool(x.token,'submit_result',envelope(j,insight(x.observation)));const q=await lab.tool(x.token,'attach_evidence',{hypothesisId:made.data.result.hypothesis.id,content:'后续材料尚无独立核验',stance:'supports'});assert.equal(q.data.evidence.assessedBy,'external_agent');const r=(await lab.req('/api/runs/'+x.run.id)).data.run;assert.equal(r.feedback.length,0);assert.equal(r.hypotheses[0].evidence[0].assessedBy,'external_agent');assert.equal(r.events.find(e=>e.type==='evidence.attached').data.evidence.assessedBy,'external_agent');});
test('bounded next-task long poll wakes only when a human queues work',async t=>{const lab=await start(t),x=await attach(lab);const p=lab.tool(x.token,'next_task',{waitMs:2000});await new Promise(r=>setTimeout(r,40));await queue(lab,x);const q=await p;assert.equal(q.status,200);assert.equal(q.data.state,'claimed');});
test('bounded idle poll returns idle and creates no analytical results',async t=>{const lab=await start(t),x=await attach(lab);const q=await lab.tool(x.token,'next_task',{waitMs:30});assert.equal(q.data.state,'idle');assert.equal((await lab.req('/api/runs/'+x.run.id)).data.run.agentJobs.length,0);});
test('two concurrent claims cannot lease the same task twice',async t=>{const lab=await start(t),x=await attach(lab);await queue(lab,x);const qs=await Promise.all([lab.tool(x.token,'next_task'),lab.tool(x.token,'next_task')]);assert.equal(qs.filter(q=>q.data.state==='claimed').length,1);});
test('release allows a new claim and invalidates the old lease token',async t=>{const lab=await start(t),x=await attach(lab);await queue(lab,x);const first=await claim(lab,x);await lab.tool(x.token,'release_task',{jobId:first.job.id,claimToken:first.claimToken});const second=await claim(lab,x);assert.notEqual(first.claimToken,second.claimToken);assert.equal((await lab.tool(x.token,'submit_result',envelope(first,{mapping:baselineMap(x.observation)}))).status,403);});
test('expired lease rejects stale completion and permits reclamation',async t=>{const lab=await start(t,{}, {leaseMs:30}),x=await attach(lab);await queue(lab,x);const first=await claim(lab,x);await new Promise(r=>setTimeout(r,60));const q=await lab.tool(x.token,'submit_result',envelope(first,{mapping:baselineMap(x.observation)}));assert.equal(q.data.code,'LEASE_EXPIRED');const second=await claim(lab,x);assert.equal(first.job.id,second.job.id);assert.notEqual(first.claimToken,second.claimToken);});
test('renewing an active task extends its lease',async t=>{const lab=await start(t),x=await attach(lab);await queue(lab,x);const first=await claim(lab,x);await new Promise(r=>setTimeout(r,5));const q=await lab.tool(x.token,'renew_task',{jobId:first.job.id,claimToken:first.claimToken});assert.ok(Date.parse(q.data.job.leaseUntil)>Date.parse(first.job.leaseUntil));});
test('events expose durable cursors and never claim that bridge heartbeat is model reasoning',async t=>{const lab=await start(t),x=await attach(lab);const a=await lab.tool(x.token,'events',{after:0});assert.ok(a.data.events.length);const b=await lab.tool(x.token,'events',{after:a.data.nextAfter});assert.equal(b.data.events.length,0);const h=await lab.req('/api/agent/heartbeat',{},x.token);assert.match(h.data.notice,/not proof/);});
test('reads preserve run bytes, and revoked/expired sessions do not silently reactivate',async t=>{const lab=await start(t),x=await attach(lab);const file=path.join(lab.home,'runs',x.run.id+'.json'),before=fs.readFileSync(file,'utf8');await lab.req('/api/runs/'+x.run.id);await lab.req('/api/agent/status',undefined,x.token);await lab.req('/api/agent/sessions');assert.equal(fs.readFileSync(file,'utf8'),before);});
test('URL client refuses remote, credential-bearing, path and redirect-like bases',()=>{for(const url of ['https://evil.example','http://127.0.0.1.evil.example:4174','http://user:pass@127.0.0.1','http://127.0.0.1/?token=secret','http://127.0.0.1/api'])assert.throws(()=>localBase(url));assert.equal(localBase('http://localhost:4174/'),'http://localhost:4174');});
test('connection files are private and cached pairing resumes without reusing the code',async t=>{const lab=await start(t);const r=(await lab.req('/api/demo',{})).data.run;const s=(await lab.req('/api/agent/sessions',{runId:r.id})).data;const file=path.join(lab.home,'private','connection.json');const a=createAgentClient({url:lab.base,pair:s.pairing.code,connectionFile:file});await a.ensure();if(process.platform!=='win32')assert.equal(fs.statSync(file).mode&0o777,0o600);const b=createAgentClient({url:lab.base,pair:s.pairing.code,connectionFile:file});assert.equal((await b.status()).session.id,s.session.id);});
test('CLI pairing, context, claim and own-result submission complete a real round trip',async t=>{const lab=await start(t);const d=JSON.parse((await cli(lab,['demo'])).stdout).run;const s=JSON.parse((await cli(lab,['agent','session',d.id])).stdout);const conn=path.join(lab.home,'cli-connection.json');const connected=await cli(lab,['agent','connect','--code',s.pairing.code,'--connection',conn]);assert.equal(connected.code,0,connected.stderr);assert.ok(!connected.stdout.includes('tao_agent_'));await cli(lab,['agent','queue',d.id,d.observations[0].id]);const job=path.join(lab.home,'job.json');assert.equal((await cli(lab,['agent','next','--connection',conn,'--out',job])).code,0);const file=path.join(lab.home,'result.json');fs.writeFileSync(file,JSON.stringify({mapping:baselineMap(d.observations[0])}));const q=await cli(lab,['agent','submit','--connection',conn,'--job-file',job,'--file',file]);assert.equal(q.code,0,q.stderr);assert.equal(JSON.parse(q.stdout).accepted,true);assert.equal((await lab.req('/api/runs/'+d.id)).data.run.mappingMeta[d.observations[0].id].provider,'external');});
test('session lifetime is enforced on the next authenticated request',async t=>{let time=Date.now();const lab=await start(t,{}, {clock:()=>time}),x=await attach(lab);time+=9*3600000;const q=await lab.tool(x.token,'status');assert.equal(q.status,401);assert.equal(q.data.code,'SESSION_EXPIRED');assert.equal((await lab.req('/api/runs/'+x.run.id)).data.run.driver.kind,'external');});
test('unused pairing codes expire and repeated bad attempts are rate limited',async t=>{let time=Date.now();const lab=await start(t,{}, {clock:()=>time});const r=(await lab.req('/api/demo',{})).data.run,s=(await lab.req('/api/agent/sessions',{runId:r.id})).data;time+=601000;assert.equal((await lab.req('/api/agent/connect',{code:s.pairing.code})).data.code,'PAIR_INVALID');for(let i=0;i<11;i++)await lab.req('/api/agent/connect',{code:'bad'});assert.equal((await lab.req('/api/agent/connect',{code:'bad'})).status,429);});
test('changing an actual frozen source or protocol rejects stale results even if a stored hash is unchanged',async t=>{const lab=await start(t),x=await attach(lab);await queue(lab,x);const j=await claim(lab,x),file=path.join(lab.home,'runs',x.run.id+'.json'),r=JSON.parse(fs.readFileSync(file));r.promptSnapshot.protocolText+='\nChanged outside the API in a test only.';fs.writeFileSync(file,JSON.stringify(r));const q=await lab.tool(x.token,'submit_result',envelope(j,{mapping:baselineMap(x.observation)}));assert.equal(q.data.code,'STALE_CONTEXT');assert.equal((await lab.req('/api/runs/'+x.run.id)).data.run.agentSubmissions.length,0);});
test('an actual observation from a different run is never readable through a scoped connection',async t=>{const lab=await start(t),x=await attach(lab),other=(await lab.req('/api/demo',{})).data.run;assert.equal((await lab.tool(x.token,'get_context',{observationId:other.observations[0].id})).status,404);const c=(await lab.tool(x.token,'get_context')).data.context;assert.ok(c.observations.every(o=>x.run.observations.some(a=>a.id===o.id)));});
test('server restart preserves paired credentials and an unexpired claimed task, not unused pairing codes',async t=>{
 const home=fs.mkdtempSync(path.join(os.tmpdir(),'tao-restart-'));let server=createLabServer({home,env:{}});await new Promise(r=>server.listen(0,'127.0.0.1',r));let base=`http://127.0.0.1:${server.address().port}`;
 const req=async(route,b,token)=>{const q=await fetch(base+route,{method:b===undefined?'GET':'POST',headers:{'content-type':'application/json',...(token?{authorization:'Bearer '+token}:{})},body:b===undefined?undefined:JSON.stringify(b)});return {status:q.status,data:await q.json()};};
 t.after(async()=>{server.closeStreams();server.closeAllConnections();await new Promise(r=>server.close(r));fs.rmSync(home,{recursive:true,force:true});});
 const lab={req,tool:(token,name,b={})=>req('/api/agent/tools/observatory_'+name,b,token)},x=await attach(lab);await queue(lab,x);const j=await claim(lab,x);const pending=(await req('/api/agent/sessions',{runId:x.run.id,role:'observer'})).data;
 server.closeStreams();server.closeAllConnections();await new Promise(r=>server.close(r));server=createLabServer({home,env:{}});await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`;
 assert.equal((await req('/api/agent/connect',{code:pending.pairing.code})).data.code,'PAIR_INVALID');assert.equal((await lab.tool(x.token,'submit_result',envelope(j,{mapping:baselineMap(x.observation)}))).data.accepted,true);assert.equal((await req('/api/runs/'+x.run.id)).data.run.traces.length,0);
});
