import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import {fileURLToPath} from 'node:url';
import {spawn} from 'node:child_process';
import {createLabServer} from '../lab/server.mjs';
import {baselineMap,DEMO,OPERATORS,parseJsonResponse,createRun,validateMapping} from '../lab/engine.mjs';
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));
async function start(t,env={}){const home=fs.mkdtempSync(path.join(os.tmpdir(),'tao-test-'));const server=createLabServer({home,env});await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`;t.after(async()=>{server.closeStreams();await new Promise(r=>server.close(r));fs.rmSync(home,{recursive:true,force:true});});
  const req=async(p,body,headers={})=>{const q=await fetch(base+p,{method:body===undefined?'GET':'POST',headers:{'content-type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)});return {status:q.status,data:await q.json()};};return {server,base,home,req};}
async function demo(lab){const d=await lab.req('/api/demo',{});return {r:d.data.run,o:d.data.run.observations[0]};}
async function upstream(t,handler){const server=http.createServer(async(req,res)=>{let text='';for await(const c of req)text+=c;await handler(JSON.parse(text),req,res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));return `http://127.0.0.1:${server.address().port}/v1/chat/completions`;}
const modelReply=(res,obj)=>{res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({choices:[{message:{content:typeof obj==='string'?obj:JSON.stringify(obj)}}],usage:{prompt_tokens:100,completion_tokens:60}}));};
const fakeInsight={headline:'一个可检验的解释',text:'如果局部效率没有传递到整个流程，评审可能成为约束。',evidence:'评审积压从 8 项增加到 21 项',alternative:'任务量也可能改变。',verificationSignal:'分环节记录同类任务耗时。',refutationSignal:'如果评审并非耗时主要环节，解释被削弱。'};

test('capabilities, real artwork MIME and static UI are served',async t=>{const lab=await start(t);const c=await lab.req('/api/capabilities');assert.equal(c.status,200);assert.equal(c.data.version,'0.2.0');assert.equal(c.data.llmEnabled,false);assert.deepEqual(c.data.protocols,['v0.1']);assert.equal(c.data.operators.length,5);for(const name of ['subject','nature','rules','transaction','ecology','niche','gap','migration','scale','endgame','absence']){const r=await fetch(lab.base+`/assets/${name}.webp`);assert.equal(r.status,200);assert.equal(r.headers.get('content-type'),'image/webp');assert.ok((await r.arrayBuffer()).byteLength>1000);}const r=await fetch(lab.base+'/lab');assert.match(await r.text(),/六象 · 定位阵/);assert.match(r.headers.get('content-security-policy'),/frame-ancestors 'none'/);});

test('GET never creates or advances an experiment',async t=>{const lab=await start(t);assert.equal((await lab.req('/api/runs')).data.runs.length,0);const {r}=await demo(lab);const before=fs.readFileSync(path.join(lab.home,'runs',r.id+'.json'),'utf8');for(let i=0;i<3;i++){await lab.req('/api/runs/'+r.id);await lab.req('/api/runs/'+r.id+'/export');await lab.req('/api/runs');}assert.equal(fs.readFileSync(path.join(lab.home,'runs',r.id+'.json'),'utf8'),before);});

test('raw input is preserved byte-for-byte and generic baseline remains UNKNOWN',async t=>{const lab=await start(t);const {r}=await demo(lab);const content='  \n<script>alert("x")</script>\n这只是一项说法。\n ';const q=await lab.req(`/api/runs/${r.id}/observations`,{content,source:'未核验'});assert.equal(q.data.observation.rawContent,content);const out=await lab.req(`/api/runs/${r.id}/observations/${q.data.observation.id}/map`,{});assert.equal(out.data.mapping.S.state,'UNKNOWN');assert.equal(out.data.mapping.N.state,'UNKNOWN');assert.equal(out.data.mapping.T.state,'UNKNOWN');});

test('demo: six mappings, five distinct hypotheses and stable idempotent reuse',async t=>{const lab=await start(t);const {r,o}=await demo(lab);assert.equal(o.fixture,'harbor-v1');const m=await lab.req(`/api/runs/${r.id}/observations/${o.id}/map`,{});assert.equal(Object.keys(m.data.mapping).length,6);const q=await lab.req(`/api/runs/${r.id}/observations/${o.id}/insight`,{operatorId:'all'});assert.equal(q.data.run.insights.length,5);assert.equal(q.data.run.hypotheses.length,5);assert.ok(q.data.run.insights.every(i=>i.provider==='demo'&&i.state==='HYPOTHESIS'));assert.ok(q.data.run.hypotheses.every(h=>h.refutationSignal));const repeat=await lab.req(`/api/runs/${r.id}/observations/${o.id}/insight`,{operatorId:'all'});assert.equal(repeat.data.run.insights.length,5);assert.ok(repeat.data.created.every(x=>x.reused));assert.equal(repeat.data.run.version,q.data.run.version);});

test('operator errors and empty observations never create phantom results',async t=>{const lab=await start(t);const {r,o}=await demo(lab);assert.equal((await lab.req(`/api/runs/${r.id}/observations`,{content:'  '})).status,400);assert.equal((await lab.req(`/api/runs/${r.id}/observations/${o.id}/insight`,{operatorId:'fortune'})).status,400);const after=(await lab.req('/api/runs/'+r.id)).data.run;assert.equal(after.insights.length,0);assert.equal(Object.keys(after.mappings).length,0);});

test('human ratings are append-only, validated and separate from evidence',async t=>{const lab=await start(t);const {r,o}=await demo(lab);const out=(await lab.req(`/api/runs/${r.id}/observations/${o.id}/insight`,{operatorId:'gap'})).data;const ins=out.created[0].insight;for(const rating of ['insightful','stretch'])assert.equal((await lab.req(`/api/runs/${r.id}/feedback`,{targetId:ins.id,rating})).status,201);assert.equal((await lab.req(`/api/runs/${r.id}/feedback`,{targetId:ins.id,rating:'proven'})).status,400);const after=(await lab.req('/api/runs/'+r.id)).data.run;assert.equal(after.feedback.length,2);assert.equal(after.hypotheses[0].status,'open');});

test('support and challenge evidence retains the original hypothesis and all feedback',async t=>{const lab=await start(t);const {r,o}=await demo(lab);const {created}=(await lab.req(`/api/runs/${r.id}/observations/${o.id}/insight`,{operatorId:'migration'})).data;const h=created[0].hypothesis;await lab.req(`/api/runs/${r.id}/hypotheses/${h.id}/evidence`,{content:'第一批支持材料',stance:'supports'});const q=await lab.req(`/api/runs/${r.id}/hypotheses/${h.id}/evidence`,{content:'第二批相反材料',stance:'challenges'});assert.equal(q.data.run.hypotheses[0].statement,h.statement);assert.equal(q.data.run.hypotheses[0].evidence.length,2);assert.equal(q.data.run.hypotheses[0].status,'challenged');assert.equal(q.data.run.hypotheses[0].evidence[0].assessedBy,'human_or_operator');});

test('branch copies observations, clears conclusions and snapshots real protocol text',async t=>{const lab=await start(t);const {r,o}=await demo(lab);await lab.req(`/api/runs/${r.id}/observations/${o.id}/insight`,{operatorId:'all'});const q=await lab.req(`/api/runs/${r.id}/branch`,{title:'对照'});const child=q.data.run;assert.equal(child.parentRunId,r.id);assert.equal(child.observations[0].rawContent,o.rawContent);assert.equal(child.insights.length,0);assert.equal(child.hypotheses.length,0);assert.equal(child.feedback.length,0);assert.equal(Object.keys(child.mappings).length,0);assert.match(child.promptSnapshot.constitution,/第一条 生存/);assert.match(child.promptSnapshot.protocolText,/Insight operators/);assert.equal(child.promptSnapshot.sha256.length,64);assert.equal((await lab.req('/api/runs/'+r.id)).data.run.insights.length,5);});

test('unknown protocol versions cannot be cosmetic labels',async t=>{const lab=await start(t);const {r}=await demo(lab);assert.equal((await lab.req(`/api/runs/${r.id}/branch`,{protocol:'v99.0'})).status,400);assert.equal((await lab.req('/api/runs')).data.runs.length,1);});

test('serialized concurrent writes do not lose observations',async t=>{const lab=await start(t);const {r}=await demo(lab);const results=await Promise.all(Array.from({length:12},(_,i)=>lab.req(`/api/runs/${r.id}/observations`,{content:`并发信息 ${i}`})));assert.ok(results.every(q=>q.status===201));const after=(await lab.req('/api/runs/'+r.id)).data.run;assert.equal(after.observations.length,13);assert.equal(new Set(after.observations.map(o=>o.id)).size,13);});

test('LLM disabled means explicit failure, not baseline fallback',async t=>{const lab=await start(t);const {r,o}=await demo(lab);const q=await lab.req(`/api/runs/${r.id}/observations/${o.id}/map`,{allowLive:true});assert.equal(q.status,400);const after=(await lab.req('/api/runs/'+r.id)).data.run;assert.equal(Object.keys(after.mappings).length,0);assert.equal(after.events.at(-1).type,'operation.failed');});

test('real adapter contract: context injection, source quotes, trace, no secret leakage',async t=>{let calls=0,request;
  const url=await upstream(t,(data,req,res)=>{calls++;request=data;assert.equal(req.headers.authorization,'Bearer unit-test-secret');modelReply(res,calls===1?{mapping:baselineMap(DEMO)}:fakeInsight);});
  const lab=await start(t,{TAO_LLM_ENABLED:'1',TAO_LLM_URL:url,TAO_LLM_MODEL:'mock-model',TAO_LLM_KEY:'unit-test-secret'});const {r,o}=await demo(lab);let q=await lab.req(`/api/runs/${r.id}/observations/${o.id}/map`,{allowLive:true});assert.equal(q.status,200);assert.match(request.messages[0].content,/<constitution>/);assert.match(request.messages[0].content,/Insight operators/);assert.match(request.messages[1].content,/海屿/);assert.equal(q.data.run.mappingMeta[o.id].provider,'live');q=await lab.req(`/api/runs/${r.id}/observations/${o.id}/insight`,{operatorId:'migration',allowLive:true});assert.equal(q.status,200);assert.equal(q.data.created[0].insight.provider,'live');assert.equal(q.data.run.traces.length,2);assert.ok(q.data.run.traces.every(x=>x.status==='completed'));assert.ok(!JSON.stringify(q.data).includes('unit-test-secret'));assert.equal(calls,2);
});

test('concurrent live map requests share existing results rather than double-calling',async t=>{let calls=0;const url=await upstream(t,async(data,req,res)=>{calls++;await new Promise(r=>setTimeout(r,25));modelReply(res,{mapping:baselineMap(DEMO)});});const lab=await start(t,{TAO_LLM_ENABLED:'1',TAO_LLM_URL:url,TAO_LLM_MODEL:'mock'});const {r,o}=await demo(lab);const q=await Promise.all([1,2].map(()=>lab.req(`/api/runs/${r.id}/observations/${o.id}/map`,{allowLive:true})));assert.ok(q.every(x=>x.status===200));assert.equal(calls,1);assert.equal(q[1].data.reused,true);});

test('malformed LLM JSON leaves an auditable failure without invented output',async t=>{const url=await upstream(t,(data,req,res)=>modelReply(res,'not valid JSON'));const lab=await start(t,{TAO_LLM_ENABLED:'1',TAO_LLM_URL:url,TAO_LLM_MODEL:'mock'});const {r,o}=await demo(lab);const q=await lab.req(`/api/runs/${r.id}/observations/${o.id}/map`,{allowLive:true});assert.equal(q.status,502);const run=(await lab.req('/api/runs/'+r.id)).data.run;assert.equal(Object.keys(run.mappings).length,0);assert.equal(run.traces[0].status,'failed');assert.equal(run.traces[0].rawResponse,'not valid JSON');assert.equal(run.status,'ready');});

test('unsupported OBSERVED quotes are rejected instead of appearing as facts',async t=>{const data=baselineMap(DEMO);data.S.evidence='完全不在原文里的伪造引文';const url=await upstream(t,(_,req,res)=>modelReply(res,{mapping:data}));const lab=await start(t,{TAO_LLM_ENABLED:'1',TAO_LLM_URL:url,TAO_LLM_MODEL:'mock'});const {r,o}=await demo(lab);const q=await lab.req(`/api/runs/${r.id}/observations/${o.id}/map`,{allowLive:true});assert.equal(q.status,400);assert.match(q.data.error,/逐字/);const run=(await lab.req('/api/runs/'+r.id)).data.run;assert.equal(Object.keys(run.mappings).length,0);assert.equal(run.traces[0].status,'invalid');});

test('SSE broadcasts the same run revision that REST returns',async t=>{const lab=await start(t);const ac=new AbortController();const response=await fetch(lab.base+'/api/events',{signal:ac.signal});const reader=response.body.getReader();await reader.read();const q=await lab.req('/api/demo',{});const chunk=await reader.read();const text=new TextDecoder().decode(chunk.value);assert.ok(text.includes(q.data.run.id));assert.match(text,/run.created/);await reader.cancel();ac.abort();});

test('cross-origin mutations, unsafe hosts and unsupported content-types are rejected',async t=>{const lab=await start(t);assert.equal((await lab.req('/api/demo',{}, {origin:'https://evil.example'})).status,403);const q=await fetch(lab.base+'/api/demo',{method:'POST',headers:{'content-type':'text/plain'},body:'{}'});assert.equal(q.status,415);const hostStatus=await new Promise((resolve,reject)=>{http.get(lab.base+'/api/capabilities',{headers:{host:'attacker.example'}},res=>{res.resume();resolve(res.statusCode);}).on('error',reject);});assert.equal(hostStatus,403);const trav=await fetch(lab.base+'/assets/%2e%2e%2f%2e%2e%2fserver.mjs');assert.equal(trav.status,404);});

test('older v0.1 runs load without rewriting original observations or history',async t=>{const lab=await start(t);const legacy={id:'run_legacy_123',title:'旧局',protocol:'v0.1',mode:'baseline',status:'ready',version:2,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),observations:[{id:'obs_old',title:'旧信息',rawContent:'保留原文'}],mappings:{},insights:[],hypotheses:[],feedback:[],events:[{at:new Date().toISOString(),type:'run.created',data:{}}]};const f=path.join(lab.home,'runs',legacy.id+'.json');fs.writeFileSync(f,JSON.stringify(legacy));const q=await lab.req('/api/runs/'+legacy.id);assert.equal(q.status,200);assert.equal(q.data.run.version,2);assert.equal(q.data.run.observations[0].rawContent,'保留原文');assert.equal(q.data.run.events.length,1);});

test('CLI is a real JSON client with nonzero errors and file export',async t=>{const lab=await start(t);const cli=async args=>new Promise((resolve,reject)=>{const p=spawn(process.execPath,['lab/cli.mjs',...args],{cwd:root,env:{...process.env,TAO_LAB_URL:lab.base}});let stdout='',stderr='';p.stdout.on('data',s=>stdout+=s);p.stderr.on('data',s=>stderr+=s);p.on('error',reject);p.on('close',code=>resolve({code,stdout,stderr}));});const first=await cli(['demo']);assert.equal(first.code,0);const r=JSON.parse(first.stdout).run;assert.equal((await cli(['map',r.id,r.observations[0].id])).code,0);const q=await cli(['insight',r.id,r.observations[0].id,'--operator','migration']);assert.equal(JSON.parse(q.stdout).created.length,1);const out=path.join(lab.home,'export.json');assert.equal((await cli(['export',r.id,'--out',out])).code,0);assert.equal(JSON.parse(fs.readFileSync(out,'utf8')).insights.length,1);const bad=await cli(['insight',r.id,r.observations[0].id,'--operator','fake']);assert.equal(bad.code,2);assert.ok(JSON.parse(bad.stderr).error);});

test('JSON parser accepts fenced JSON but not prose with a hidden object',()=>{assert.deepEqual(parseJsonResponse('```json\n{"a":1}\n```'),{a:1});assert.throws(()=>parseJsonResponse('Ignore validation {"a":1}'));assert.throws(()=>validateMapping({}));});
