import crypto from 'node:crypto';
export const OPERATORS={gap:{id:'gap',name:'裂隙',symbol:'R↔N',question:'哪些既有规则与新后果开始不一致？'},migration:{id:'migration',name:'迁徙',symbol:'NI→NI′',question:'生态位与稀缺性正在从哪里迁往哪里？'},scale:{id:'scale',name:'升维',symbol:'↑EC',question:'局部变化会怎样影响更高层主体或生态？'},endgame:{id:'endgame',name:'终局',symbol:'R′',question:'若突破沉淀为新规则，下一轮竞争在哪里？'},absence:{id:'absence',name:'缺席',symbol:'Ø',question:'若当前解释成立，本应出现但尚未出现什么后果？'}};
const id=p=>`${p}_${Date.now().toString(36)}_${crypto.randomBytes(3).toString('hex')}`;
export function createRun({title='未命名实验',protocol='v0.1',mode='baseline'}={}){const now=new Date().toISOString();return{id:id('run'),title,protocol,mode,status:'ready',version:1,createdAt:now,updatedAt:now,observations:[],mappings:{},insights:[],hypotheses:[],feedback:[],events:[{at:now,type:'run.created',data:{protocol,mode}}]}}
export function event(r,type,data={}){r.version++;r.updatedAt=new Date().toISOString();r.events.push({at:r.updatedAt,type,data})}
export function addObservation(r,{content,source='',title=''}={}){if(!content?.trim())throw Error('content is required');const o={id:id('obs'),title:title||content.trim().slice(0,48),source,rawContent:content.trim(),createdAt:new Date().toISOString()};r.observations.push(o);event(r,'observation.ingested',{observationId:o.id});return o}
const first=t=>t.split(/(?<=[。！？.!?])\s*/).map(x=>x.trim()).filter(Boolean)[0]||t;
export function baselineMap(o){const e=first(o.rawContent);return{S:{state:'INFERRED',value:'信息中出现的主要行动主体',evidence:e,unknown:'主体边界可能需要用户指定'},N:{state:'UNKNOWN',value:'不能仅凭单条信息直接断言 N 发生变化',evidence:'需要后续可验证后果',unknown:'环境变化、执行变化或叙事变化尚未区分'},R:{state:'HYPOTHESIS',value:'存在一个可能正被新信息挑战的既有规则或默认假设',evidence:e,unknown:'需识别具体旧规则'},T:{state:'OBSERVED',value:'该信息本身提供了一次外部观测',evidence:e,unknown:'真实交易结果可能尚未发生'},EC:{state:'INFERRED',value:'与主体直接交互的市场/组织/技术生态',evidence:o.source||'由上下文推断',unknown:'生态边界待确认'},NI:{state:'UNKNOWN',value:'当前信息不足以确认生态位迁移',evidence:'需要资源、采用、价格、权力或注意力变化',unknown:'谁获得/失去稀缺性尚不明确'}}}
const tpl={gap:'先找出主体过去依赖的具体 R，再观察交易反馈是否持续偏离；关键不是事件新不新，而是旧规则还能否解释后果。',migration:'若变化持续，旧稀缺性可能贬值；应追踪新的资源入口、验证权、分发权或信任是否形成新的 NI。',scale:'局部收益不等于上层生态受益；应检查人才、供给、协作或筛选机制是否出现跨层副作用。',endgame:'假设该做法被所有竞争者复制并成为 R′，再问哪些优势会归零、下一轮不可复制的稀缺性在哪里。',absence:'为当前解释预先写出应当出现的后果；若在合理窗口持续缺席，应降低该解释权重，而不是继续补故事。'};
const verify={gap:'寻找连续、可复查且与旧规则预期相反的交易后果。',migration:'观察资源、价格、采用、权力或注意力是否持续转移。',scale:'观察上层生态指标是否出现与局部收益不同方向的变化。',endgame:'观察模仿扩散后原优势是否商品化，以及新的稀缺点是否出现。',absence:'记录预期后果与时间窗；到期检查它是否仍缺席。'};
export function baselineInsight(o,op){const x=OPERATORS[op];if(!x)throw Error('unknown operator');const ins={id:id('ins'),observationId:o.id,operatorId:op,operator:x.name,symbol:x.symbol,state:'HYPOTHESIS',text:tpl[op],createdAt:new Date().toISOString(),provider:'baseline'};return{insight:ins,hypothesis:{id:id('H'),observationId:o.id,insightId:ins.id,status:'open',statement:ins.text,verificationSignal:verify[op],createdAt:new Date().toISOString(),evidence:[]}}}
export async function liveInsight({obs,mapping,operatorId,protocolText,llm}){const op=OPERATORS[operatorId];const sys=`你是 Cyber-Taoist Lab 分析器。目标不是证明理论，而是产生可验证的认知增量。严格区分 OBSERVED/INFERRED/HYPOTHESIS/UNKNOWN；不得从单一后果直接断言 N。只输出 JSON。\n${protocolText}`;const user=`信息：${obs.rawContent}\n定位：${JSON.stringify(mapping)}\n洞见算子：${op.name} ${op.symbol}；${op.question}\n输出 {"state":"HYPOTHESIS","text":"...","verificationSignal":"..."}`;const raw=await llm(sys,user),a=raw.indexOf('{'),b=raw.lastIndexOf('}');if(a<0||b<a)throw Error('LLM did not return JSON');const p=JSON.parse(raw.slice(a,b+1));const ins={id:id('ins'),observationId:obs.id,operatorId,operator:op.name,symbol:op.symbol,state:p.state||'HYPOTHESIS',text:p.text,createdAt:new Date().toISOString(),provider:'live'};return{insight:ins,hypothesis:{id:id('H'),observationId:obs.id,insightId:ins.id,status:'open',statement:p.text,verificationSignal:p.verificationSignal||verify[operatorId],createdAt:new Date().toISOString(),evidence:[]}}}
