import http from'node:http';import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';import{createRun,addObservation,event,baselineMap,baselineInsight,liveInsight,OPERATORS}from'./engine.mjs';
const dir=path.dirname(fileURLToPath(import.meta.url)),pub=path.join(dir,'public'),home=path.resolve(process.env.TAO_LAB_HOME||'.tao-lab');fs.mkdirSync(path.join(home,'runs'),{recursive:true});const port=+(process.env.PORT||4174),live=process.env.TAO_LLM_ENABLED==='1';
const rp=id=>path.join(home,'runs',id+'.json'),save=r=>fs.writeFileSync(rp(r.id),JSON.stringify(r,null,2)),load=id=>JSON.parse(fs.readFileSync(rp(id),'utf8')),list=()=>fs.readdirSync(path.join(home,'runs')).filter(x=>x.endsWith('.json')).map(x=>load(x.slice(0,-5))).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));
async function body(req){let s='';for await(const c of req){s+=c;if(s.length>2e6)throw Error('body too large')}return s?JSON.parse(s):{}}
const send=(res,n,o)=>{res.writeHead(n,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(o))};
async function llm(system,user){const url=process.env.TAO_LLM_URL,model=process.env.TAO_LLM_MODEL,key=process.env.TAO_LLM_KEY;if(!url||!model)throw Error('TAO_LLM_URL and TAO_LLM_MODEL required');const q=await fetch(url,{method:'POST',headers:{'content-type':'application/json',...(key?{authorization:`Bearer ${key}`}:{})},body:JSON.stringify({model,messages:[{role:'system',content:system},{role:'user',content:user}],temperature:.2})});if(!q.ok)throw Error(`LLM ${q.status}: ${await q.text()}`);const j=await q.json();return j.choices?.[0]?.message?.content??j.output_text??''}
const protocol=()=>{try{return fs.readFileSync(path.resolve('content/PROTOCOL-v0.1.md'),'utf8')}catch{return''}};
async function api(req,res,u){if(req.method==='GET'&&u.pathname==='/api/capabilities')return send(res,200,{version:'0.1.0',protocol:'v0.1',llmEnabled:live,operators:Object.values(OPERATORS)});if(req.method==='GET'&&u.pathname==='/api/runs')return send(res,200,{runs:list()});if(req.method==='POST'&&u.pathname==='/api/runs'){const r=createRun(await body(req));save(r);return send(res,201,{run:r,viewerUrl:`/lab?run=${r.id}`})}const m=u.pathname.match(/^\/api\/runs\/([^/]+)(?:\/(.*))?$/);if(!m)return false;const r=load(m[1]),tail=m[2]||'';if(req.method==='GET'&&!tail)return send(res,200,{run:r});if(req.method==='POST'&&tail==='observations'){const o=addObservation(r,await body(req));save(r);return send(res,201,{observation:o,run:r})}let z=tail.match(/^observations\/([^/]+)\/map$/);if(req.method==='POST'&&z){const o=r.observations.find(x=>x.id===z[1]);if(!o)throw Error('observation not found');r.mappings[o.id]=baselineMap(o);event(r,'observation.mapped',{observationId:o.id});save(r);return send(res,200,{mapping:r.mappings[o.id],run:r})}z=tail.match(/^observations\/([^/]+)\/insight$/);if(req.method==='POST'&&z){const b=await body(req),o=r.observations.find(x=>x.id===z[1]);if(!o)throw Error('observation not found');const map=r.mappings[o.id]||baselineMap(o);r.mappings[o.id]=map;const ops=b.operatorId==='all'?Object.keys(OPERATORS):[b.operatorId],made=[];for(const op of ops){let x;if(b.allowLive){if(!live)throw Error('live LLM disabled by server');x=await liveInsight({obs:o,mapping:map,operatorId:op,protocolText:protocol(),llm})}else x=baselineInsight(o,op);r.insights.push(x.insight);r.hypotheses.push(x.hypothesis);made.push(x)}event(r,'insight.generated',{observationId:o.id,operators:ops,live:!!b.allowLive});save(r);return send(res,200,{created:made,run:r})}if(req.method==='POST'&&tail==='feedback'){const b=await body(req);r.feedback.push({id:'fb_'+Date.now(),at:new Date().toISOString(),...b});event(r,'feedback.added',{targetId:b.targetId,rating:b.rating});save(r);return send(res,201,{run:r})}if(req.method==='POST'&&tail==='branch'){const b=await body(req),n=structuredClone(r);n.id='run_'+Date.now().toString(36)+'_'+Math.random().toString(16).slice(2,8);n.title=b.title||r.title+' · branch';n.protocol=b.protocol||r.protocol;n.createdAt=n.updatedAt=new Date().toISOString();n.version=1;n.events=[{at:n.createdAt,type:'run.branched',data:{from:r.id,protocol:n.protocol}}];save(n);return send(res,201,{run:n,viewerUrl:`/lab?run=${n.id}`})}if(req.method==='GET'&&tail==='export'){res.writeHead(200,{'content-type':'application/json','content-disposition':`attachment; filename=${r.id}.json`});return res.end(JSON.stringify(r,null,2))}return false}
function staticFile(req,res,u){let p=u.pathname==='/'||u.pathname==='/lab'?'/index.html':u.pathname;p=path.normalize(p).replace(/^\.\.(\/|\\)/,'');const f=path.join(pub,p);if(!f.startsWith(pub)||!fs.existsSync(f)){res.writeHead(404);return res.end('not found')}const ext=path.extname(f);res.writeHead(200,{'content-type':ext==='.css'?'text/css; charset=utf-8':ext==='.js'?'text/javascript; charset=utf-8':'text/html; charset=utf-8'});fs.createReadStream(f).pipe(res)}
http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname.startsWith('/api/')){const ok=await api(req,res,u);if(ok!==false)return;return send(res,404,{error:'not found'})}staticFile(req,res,u)}catch(e){send(res,400,{error:e.message})}}).listen(port,'127.0.0.1',()=>console.log(`Tao Lab v0.1 http://127.0.0.1:${port}/lab`));
